### PR TITLE
Dry v coercion issues

### LINKED ISSUE #380: DateTime validation with DateTime coercion
When I define a property with `DateTime` type and also a validation for `:date_time?` I receive an error in my specs.

```RUBY
property  :starts_at, type: Types::Form::DateTime

validation :default do
  required(:starts_at).filled(:date_time?)
end
```

I receive the following stack trace:
```
NoMethodError:
    undefined method `downcase' for Mon, 30 May 2016 00:00:00 +0000:DateTime
# timecop-0.8.1/lib/timecop/time_extensions.rb:101:in `parse_with_mock_date'
# dry-types-0.8.0/lib/dry/types/coercions.rb:17:in `to_date_time'
# dry-types-0.8.0/lib/dry/types/constructor.rb:33:in `[]'
# dry-types-0.8.0/lib/dry/types/constructor.rb:33:in `try'
# dry-types-0.8.0/lib/dry/types/safe.rb:16:in `try'
# dry-types-0.8.0/lib/dry/types/hash/schema.rb:85:in `block in call'
# dry-types-0.8.0/lib/dry/types/hash/schema.rb:83:in `each'
# dry-types-0.8.0/lib/dry/types/hash/schema.rb:83:in `each_with_object'
# dry-types-0.8.0/lib/dry/types/hash/schema.rb:83:in `call'
# dry-types-0.8.0/lib/dry/types/hash/schema.rb:24:in `try'
# dry-types-0.8.0/lib/dry/types/hash/schema.rb:73:in `try'
# dry-types-0.8.0/lib/dry/types/constructor.rb:33:in `try'
# dry-types-0.8.0/lib/dry/types/safe.rb:16:in `try'
# dry-types-0.8.0/lib/dry/types/safe.rb:11:in `call'
# dry-validation-0.8.0/lib/dry/validation/schema.rb:253:in `call'
# reform-2.2.1/lib/reform/form/dry.rb:38:in `call'
# reform-2.2.1/lib/reform/validation/groups.rb:57:in `block in call'
# reform-2.2.1/lib/reform/validation/groups.rb:51:in `each'
# reform-2.2.1/lib/reform/validation/groups.rb:51:in `call'
# reform-2.2.1/lib/reform/validation.rb:36:in `valid?'
# reform-2.2.1/lib/reform/contract/validate.rb:18:in `validate!'
# reform-2.2.1/lib/reform/contract/validate.rb:10:in `validate'
# reform-2.2.1/lib/reform/form/validate.rb:23:in `validate'
```

### PR DESCRIPTION
**Pull request by fran-worley**
This cleans up how we build dry-validation schemas and adds a few more test cases.

Also fixes #380 .

### CODE REVIEW

**Comment by fran-worley** [comment]
@apotonick are you happy with this? I've tested it against the latest dry-validation and it still holds up.

**Comment by apotonick** [comment]
By changing `Groups::Result` you break the ActiveModel implementation. Why is this API-change necessary?

**Comment by fran-worley** [comment]
Didn't realise that caused issues with ActiveModel. The only reason I changed it was because that parameter isn't needed for dry-v. I'll stick it back in to maintain the API.

**Comment by fran-worley** [comment]
Done :)

**Pull request merged**
