### PR TITLE
Add travis-ci badge

### PR DESCRIPTION
**Pull request by dimonzozo**

### CODE REVIEW

**Comment by apotonick** [comment]
Thanks Dimi, but I find this badge culture completely pointless. :stuck_out_tongue_winking_eye:

**Comment by dimonzozo** [comment]
Hi, @apotonick. Adding this badge had point to have easy way to check build status and find a project on Travis-Ci. This wasn't just blind badge culture obey. 

If you hate badges so much can we just add a link? :)

**Comment by apotonick** [comment]
Haha, all good @dimonzozo ! Out of curiosity: how do you use build statuses? Do you evaluate gems by checking the CI coverage or anything? I'm just eager to learn how developers use builds. BTW, finding projects on travis is `http://travis-ci.org/author/gem` ?

**Comment by fernandes** [comment]
my 2 cents

I evaluate gems seeing build status and coverage, for 2 reasons:

* Build status show me that its less probable shit happens on production, having always a green build on master show maintainer is worried about the project, its really weird check a project on GH and build is with errors or broken for days
* But a green build with 10% coverage makes no sense, so coverage is great for a birds view on project

If both points are ok, I go trough the source code, if they don't I try to find another solution :kissing:

**Comment by bolshakov** [comment]
It's also very useful to ensure that a build is failing not only in my local environment. In that case badge helps me to save time by fixing problems not related to my changes

**Comment by dimonzozo** [comment]
@apotonick, for some gems is not easy to say what current version is, so gemspec badge is good helper in this case.

* Build status badge helps to quickly find out build status and make sure it was green before my changes
* As @fernandes said coverage badge is helping to understand test suite quality

**Comment by bolshakov** [comment]
Good point about gemspec badge! Recently I decided to first time try `cells` gem. I go to it's github page and found notice:

```
This is not Cells 3.x!

Temporary note: This is the README and API for Cells 4.
```

Since I'm new user of cells, I decided that the latest stable version of gem is 3.x and I'm reading docs for not yet released version.

But after visiting rubygems I found that latest released version is 4.x. So gemspec badge may help me to save some time.

**Comment by apotonick** [comment]
These are all valid points. @bolshakov  or @dimonzozo, can one of you add the gem version badge? Does that show the most current version? That would be super helpful haha.

**Comment by bolshakov** [comment]
Easy as pie:

[Gem Version](http://badge.fury.io/rb/reform)

**Comment by apotonick** [comment]
Pull request, @bolshakov !

**Pull request merged**
