### PR TITLE
ADD case_sensitive: false to unique validation

### PR DESCRIPTION
**Pull request by samstickland**
This adds the option `case_sensitive: false` to UniqueValidator.
    
Example Usage:
    
`validates :title, unique: { case_sensitive: false }`

Tests included.

### CODE REVIEW

**Comment by samstickland** [comment]
OK, I'm going to need some help with the failed Travis-CI build. Even for the vanilla v2.1.1 tag I can't successfully run all the tests - there's already some commentary for this in this issue: https://github.com/apotonick/reform/issues/368#issuecomment-225506968

**Comment by apotonick** [comment]
This needs to go to `reform-rails`, please. :beers:

**Comment by samstickland** [comment]
You mean the whole UniqueValidator needs to move?

2016-06-15 9:30 GMT+01:00 Nick Sutterer <notifications@github.com>:

**Comment by apotonick** [comment]
It already has! https://github.com/trailblazer/reform-rails/blob/master/lib/reform/form/validation/unique_validator.rb :grimacing:

**Comment by fran-worley** [comment]
@samstickland I'm going to close this as you'll need to move it to reform-rails.

**Comment by samstickland** [comment]
Sure. Shouldn't the unique-validator code be deleted from reform then?

2016-07-05 13:17 GMT+01:00 Fran Worley <notifications@github.com>:

**Comment by fran-worley** [comment]
Indeed. https://github.com/apotonick/reform/commit/8b2391f51c3e72e4df2d9067b257d973f3c71ad0

**Pull request closed without merging**
