### PR TITLE
Improve dry integration

### PR DESCRIPTION
**Pull request by fran-worley**
1) provide a reform base schema which adds `option :form`
2) add `schema_class` as an option on a validation group which will be used instead of the reform base class

### CODE REVIEW

**Comment by fran-worley** [comment]
@apotonick I know that this can't be merged yet as it messes with the group API which will break reform-rails. Any ideas?

**Comment by fran-worley** [comment]
I've drafted a PR for reform-rails to migrate the AM methods and enable passing options to Group.new. Just need to fix a pre-existing failure before I publish it

**Comment by fran-worley** [comment]
Fixes #378

**Comment by rosskevin** [comment]
@fran-worley I'm using a lot of schema extension, it might be nice to shorten `schema_class: Foo::Schema` to `schema: Foo::Schema` since it is likely to look like a class reference anyway.  

Also, since using the `schema` option, it seems (from reading the code) that I need to name every group. It would be nice if it the dsl would see I am using an option and not make me pass `:default` as the group name.

Please correct me if I've misunderstood any of the above.

**Comment by fran-worley** [comment]
Noted on the option name. Happy to change. You shouldn't have to pass in a name to every group. It defaults to :default and this branch makes no changes there.

**Comment by rosskevin** [comment]
I've just confirmed that the earlier 70013bb482fe6ab329e225aa1d7b20f5ca558d29 fails when you use `schema_class` without a group name (none of my base predicates are found).  I'll pull this latest and give it another shot.

**Comment by rosskevin** [comment]
Group name is required when using `schema_class` on latest 3746bf23ec8478f8923a5e4f9ef70330c518a76c as well.

**Comment by fran-worley** [comment]
@rosskevin You are quite right, now fixed. I've also renamed the option to just :schema

**Pull request merged**
